// Build information declarations
// Values are defined in build_info.cpp (generated by Makefile)

#ifndef BUILD_INFO_H
#define BUILD_INFO_H

extern const char* GIT_COMMIT;
extern const char* BUILD_DATE;

#endif
