"""LED Topology Protocol library.

This package provides the core functionality for implementing LTP sources,
sinks, and controllers.
"""

from libltp.addr import (
    address_family,
    create_dual_stack_tcp_socket,
    create_dual_stack_udp_socket,
    dual_stack_bind_address,
    format_address_port,
    get_local_ip,
    is_ipv4,
    is_ipv6,
    normalize_ipv6,
)
from libltp.controls import (
    ActionControl,
    ArrayControl,
    BooleanControl,
    ColorControl,
    Control,
    ControlRegistry,
    ControlValidationError,
    EnumControl,
    EnumOption,
    NumberControl,
    StringControl,
    control_from_dict,
    controls_from_list,
)
from libltp.deviceauth import (
    ClaimSession,
    DeviceAuthError,
    DeviceAuthGuard,
    PRIVILEGED_TYPES,
)
from libltp.siphash import siphash24, siphash24_bytes, siphash24_hex
from libltp.discovery import (
    ControllerAdvertiser,
    DiscoveredDevice,
    ServiceAdvertiser,
    ServiceBrowser,
    SinkAdvertiser,
    SourceAdvertiser,
)
from libltp.protocol import (
    DataPacket,
    Message,
    ProtocolError,
    ScalarDataPacket,
    capability_request,
    capability_response,
    control_changed,
    control_get,
    control_get_response,
    control_set,
    control_set_response,
    create_matrix_buffer,
    create_pixel_buffer,
    create_scalar_buffer,
    error_message,
    input_event,
    pixel_read,
    pixel_read_response,
    stream_control,
    stream_setup,
    stream_setup_response,
    subscribe,
    subscribe_response,
)
from libltp.topology import (
    PixelBuffer,
    TopologyMapper,
    create_custom_topology,
    create_linear_topology,
    create_matrix_topology,
    scale_buffer,
    topology_from_dict,
)
from libltp.transport import (
    ControlClient,
    ControlConnection,
    ControlServer,
    DataReceiver,
    DataSender,
    StreamManager,
)
from libltp.types import (
    Channel,
    ChannelArray,
    ColorFormat,
    Coordinate,
    CustomTopology,
    DataFormat,
    DataType,
    DeviceInfo,
    DeviceType,
    Encoding,
    ErrorCode,
    LinearTopology,
    MatrixOrigin,
    MatrixOrder,
    MatrixTopology,
    MessageType,
    MirrorMode,
    PROTOCOL_VERSION,
    Route,
    ScalarFormat,
    ScalarFrameHeader,
    ScaleMode,
    SERVICE_TYPE_CONTROLLER,
    SERVICE_TYPE_SINK,
    SERVICE_TYPE_SOURCE,
    SinkCapabilities,
    SourceCapabilities,
    SourceMode,
    SourceType,
    StreamAction,
    StreamConfig,
    Topology,
    TopologyType,
    Transform,
)

__version__ = "0.1.0"

__all__ = [
    # Address utilities
    "address_family",
    "create_dual_stack_tcp_socket",
    "create_dual_stack_udp_socket",
    "dual_stack_bind_address",
    "format_address_port",
    "get_local_ip",
    "is_ipv4",
    "is_ipv6",
    "normalize_ipv6",
    # Types
    "Channel",
    "ChannelArray",
    "ColorFormat",
    "Coordinate",
    "CustomTopology",
    "DataFormat",
    "DataType",
    "DeviceInfo",
    "DeviceType",
    "Encoding",
    "ErrorCode",
    "LinearTopology",
    "MatrixOrigin",
    "MatrixOrder",
    "MatrixTopology",
    "MessageType",
    "MirrorMode",
    "PROTOCOL_VERSION",
    "Route",
    "ScalarFormat",
    "ScalarFrameHeader",
    "ScaleMode",
    "SERVICE_TYPE_CONTROLLER",
    "SERVICE_TYPE_SINK",
    "SERVICE_TYPE_SOURCE",
    "SinkCapabilities",
    "SourceCapabilities",
    "SourceMode",
    "SourceType",
    "StreamAction",
    "StreamConfig",
    "Topology",
    "TopologyType",
    "Transform",
    # Controls
    "ActionControl",
    "ArrayControl",
    "BooleanControl",
    "ColorControl",
    "Control",
    "ControlRegistry",
    "ControlValidationError",
    "EnumControl",
    "EnumOption",
    "NumberControl",
    "StringControl",
    "control_from_dict",
    "controls_from_list",
    # Protocol
    "DataPacket",
    "Message",
    "ProtocolError",
    "ScalarDataPacket",
    "capability_request",
    "capability_response",
    "control_changed",
    "control_get",
    "control_get_response",
    "control_set",
    "control_set_response",
    "create_matrix_buffer",
    "create_pixel_buffer",
    "create_scalar_buffer",
    "error_message",
    "input_event",
    "pixel_read",
    "pixel_read_response",
    "stream_control",
    "stream_setup",
    "stream_setup_response",
    "subscribe",
    "subscribe_response",
    # Discovery
    "ControllerAdvertiser",
    "DiscoveredDevice",
    "ServiceAdvertiser",
    "ServiceBrowser",
    "SinkAdvertiser",
    "ClaimSession",
    "DeviceAuthError",
    "DeviceAuthGuard",
    "PRIVILEGED_TYPES",
    "siphash24",
    "siphash24_bytes",
    "siphash24_hex",
    "SourceAdvertiser",
    # Transport
    "ControlClient",
    "ControlConnection",
    "ControlServer",
    "DataReceiver",
    "DataSender",
    "StreamManager",
    # Topology
    "PixelBuffer",
    "TopologyMapper",
    "create_custom_topology",
    "create_linear_topology",
    "create_matrix_topology",
    "scale_buffer",
    "topology_from_dict",
]
