"""LED Topology Protocol library.

This package provides the core functionality for implementing LTP sources,
sinks, and controllers.
"""

from libltp.controls import (
    ActionControl,
    ArrayControl,
    BooleanControl,
    ColorControl,
    Control,
    ControlRegistry,
    ControlValidationError,
    EnumControl,
    EnumOption,
    NumberControl,
    StringControl,
    control_from_dict,
    controls_from_list,
)
from libltp.discovery import (
    ControllerAdvertiser,
    DiscoveredDevice,
    ServiceAdvertiser,
    ServiceBrowser,
    SinkAdvertiser,
    SourceAdvertiser,
)
from libltp.protocol import (
    DataPacket,
    Message,
    ProtocolError,
    capability_request,
    capability_response,
    control_changed,
    control_get,
    control_get_response,
    control_set,
    control_set_response,
    create_matrix_buffer,
    create_pixel_buffer,
    error_message,
    stream_control,
    stream_setup,
    stream_setup_response,
    subscribe,
    subscribe_response,
)
from libltp.topology import (
    PixelBuffer,
    TopologyMapper,
    create_custom_topology,
    create_linear_topology,
    create_matrix_topology,
    scale_buffer,
    topology_from_dict,
)
from libltp.transport import (
    ControlClient,
    ControlConnection,
    ControlServer,
    DataReceiver,
    DataSender,
    StreamManager,
)
from libltp.types import (
    ColorFormat,
    Coordinate,
    CustomTopology,
    DeviceInfo,
    DeviceType,
    Encoding,
    ErrorCode,
    LinearTopology,
    MatrixOrigin,
    MatrixOrder,
    MatrixTopology,
    MessageType,
    MirrorMode,
    PROTOCOL_VERSION,
    Route,
    ScaleMode,
    SERVICE_TYPE_CONTROLLER,
    SERVICE_TYPE_SINK,
    SERVICE_TYPE_SOURCE,
    SinkCapabilities,
    SourceCapabilities,
    SourceMode,
    SourceType,
    StreamAction,
    StreamConfig,
    TopologyType,
    Transform,
)

__version__ = "0.1.0"

__all__ = [
    # Types
    "ColorFormat",
    "Coordinate",
    "CustomTopology",
    "DeviceInfo",
    "DeviceType",
    "Encoding",
    "ErrorCode",
    "LinearTopology",
    "MatrixOrigin",
    "MatrixOrder",
    "MatrixTopology",
    "MessageType",
    "MirrorMode",
    "PROTOCOL_VERSION",
    "Route",
    "ScaleMode",
    "SERVICE_TYPE_CONTROLLER",
    "SERVICE_TYPE_SINK",
    "SERVICE_TYPE_SOURCE",
    "SinkCapabilities",
    "SourceCapabilities",
    "SourceMode",
    "SourceType",
    "StreamAction",
    "StreamConfig",
    "TopologyType",
    "Transform",
    # Controls
    "ActionControl",
    "ArrayControl",
    "BooleanControl",
    "ColorControl",
    "Control",
    "ControlRegistry",
    "ControlValidationError",
    "EnumControl",
    "EnumOption",
    "NumberControl",
    "StringControl",
    "control_from_dict",
    "controls_from_list",
    # Protocol
    "DataPacket",
    "Message",
    "ProtocolError",
    "capability_request",
    "capability_response",
    "control_changed",
    "control_get",
    "control_get_response",
    "control_set",
    "control_set_response",
    "create_matrix_buffer",
    "create_pixel_buffer",
    "error_message",
    "stream_control",
    "stream_setup",
    "stream_setup_response",
    "subscribe",
    "subscribe_response",
    # Discovery
    "ControllerAdvertiser",
    "DiscoveredDevice",
    "ServiceAdvertiser",
    "ServiceBrowser",
    "SinkAdvertiser",
    "SourceAdvertiser",
    # Transport
    "ControlClient",
    "ControlConnection",
    "ControlServer",
    "DataReceiver",
    "DataSender",
    "StreamManager",
    # Topology
    "PixelBuffer",
    "TopologyMapper",
    "create_custom_topology",
    "create_linear_topology",
    "create_matrix_topology",
    "scale_buffer",
    "topology_from_dict",
]
